import type { ComplaintSummary, FullAnalysis } from '../store';

/**
 * Builds a lightweight FullAnalysis from a ComplaintSummary when the backend
 * is unavailable. Used by Triage, Supervisor, and Complaints detail views.
 */
export function syntheticAnalysis(s: ComplaintSummary): FullAnalysis {
  const ticketId = s.ticket_id ?? `OPR-${s.complaint_id.replace(/[^A-Z0-9]/gi, '').slice(-10).padStart(10, '0')}`;
  return {
    complaint_id: s.complaint_id,
    status: s.status,
    submitted_at: s.submitted_at,
    completed_at: s.completed_at,
    complaint: {
      narrative: s.narrative_preview,
      product: s.product ?? undefined,
      channel: s.channel,
      customer_state: s.customer_state ?? undefined,
      tags: s.tags,
    },
    classification: s.product ? {
      product: s.product,
      sub_product: '',
      issue: s.issue ?? '',
      sub_issue: '',
      severity: s.severity ?? 'LOW',
      sentiment_score: 0.5,
      urgency: s.priority ?? 'MEDIUM',
      confidence: 0.85,
      key_entities: [],
      reasoning: 'Derived from synthetic seed data.',
    } : null,
    compliance_risk: {
      risk_score: s.risk_score ?? 50,
      risk_level: s.risk_level ?? 'MEDIUM',
      flags: [],
      applicable_regulations: s.tags.filter((t) => t === t.toUpperCase() && t.length <= 6),
      requires_escalation: s.risk_level === 'CRITICAL',
      reasoning: `Risk level ${s.risk_level} based on response pattern and dispute status.`,
    },
    routing: s.assigned_team ? {
      assigned_team: s.assigned_team,
      assigned_tier: 'T1',
      priority: s.priority ?? 'MEDIUM',
      sla_hours: s.risk_level === 'CRITICAL' ? 4 : s.risk_level === 'HIGH' ? 24 : 72,
      escalation_path: [],
      requires_immediate_attention: s.risk_level === 'CRITICAL',
      reasoning: `Routed to ${s.assigned_team} based on product classification.`,
    } : null,
    resolution: {
      action_plan: [
        'Review complaint narrative',
        'Verify account records',
        'Contact consumer within SLA window',
      ],
      customer_response: 'We have received your complaint and are reviewing it promptly.',
      internal_notes: 'Synthetic seed — full AI resolution not available offline.',
      preventive_recommendations: [],
      estimated_resolution_days: s.risk_level === 'CRITICAL' ? 1 : 5,
      remediation_amount: null,
      reasoning: 'Standard resolution path for product category.',
    },
    qa_validation: {
      overall_score: 0.82,
      passed: s.risk_level !== 'CRITICAL',
      checks: [{ check_name: 'Completeness', passed: true, details: 'All required fields present' }],
      improvements: [],
      reasoning: 'Auto-validated by synthetic pipeline.',
    },
    review_gate: {
      needs_human_review: s.needs_human_review,
      review_reason_codes: s.review_reason_codes ?? [],
      queues: s.needs_human_review ? ['supervisor'] : [],
      sla_breach_risk: s.sla_breach_risk,
      status: s.needs_human_review ? 'pending_review' : 'auto_resolved',
      because: s.needs_human_review ? 'Critical risk requires supervisor review.' : 'Auto-resolved.',
    },
    customer_profile: {
      customer_id: s.customer_id ?? `CUST-${s.complaint_id}`,
      full_name: 'Demo Customer',
      segment: 'Prime',
      service_tier: 'Standard',
      credit_score: 712,
      delinquency_days: s.risk_level === 'CRITICAL' ? 38 : 8,
      default_probability: s.risk_level === 'CRITICAL' ? 0.46 : 0.14,
      previous_complaints_count: s.needs_human_review ? 2 : 0,
      prior_regulatory_flags: s.risk_level === 'CRITICAL' ? 1 : 0,
      account_tenure_months: 54,
      annual_income_usd: 96000,
      relationship_value_usd: 18400,
      open_products_count: 3,
      open_products: [s.product ?? 'Checking account', 'Savings account', 'Credit card'],
      deposit_balance_usd: 11240,
      revolving_balance_usd: 4800,
      loan_balance_usd: 22750,
      credit_utilization_ratio: 0.31,
      autopay_enrolled: true,
      hardship_program: false,
      kyc_tier: 'KYC3',
      fraud_watch: s.risk_level === 'CRITICAL',
      state: s.customer_state ?? null,
      preferred_channel: s.channel,
      next_payment_due: new Date().toISOString().slice(0, 10),
    },
    internal_teams: {
      primary_team: {
        team_code: 'OPS',
        team_name: s.assigned_team ?? 'Retail Banking Operations Team',
        queue: 'Complaint Operations',
        priority: s.priority ?? 'P3_MEDIUM',
        sla_hours: s.risk_level === 'CRITICAL' ? 4 : s.risk_level === 'HIGH' ? 24 : 48,
        work_item_status: 'active',
      },
      handoffs: s.needs_human_review ? [{
        team_code: 'QA',
        team_name: 'Quality Assurance & Controls Team',
        queue: 'Controls Review',
        handoff_reason: 'Fallback synthetic analysis marked the case for manual review.',
        status: 'queued',
      }] : [],
      team_catalog: [],
      data_bundle: {
        customer_profile: true,
        credit_risk: true,
        delinquency: true,
        account_overview: true,
        previous_complaints: true,
        complaint_narrative: true,
        regulatory_flags: true,
      },
    },
    root_cause: {
      code: 'service_failure',
      label: 'Service Failure',
      reason: 'Synthetic fallback inferred a service-handling breakdown from the complaint summary.',
    },
    ticket: {
      ticket_id: ticketId,
      complaint_id: s.complaint_id,
      customer_id: s.customer_id ?? `CUST-${s.complaint_id}`,
      status: s.needs_human_review ? 'pending_supervisor' : 'in_progress',
      stage: s.needs_human_review ? 'Supervisor Review' : 'Team Investigation',
      owner_team: s.assigned_team ?? 'Retail Banking Operations Team',
      queue: 'Complaint Operations',
      priority: s.priority ?? 'P3_MEDIUM',
      created_at: s.submitted_at,
      updated_at: s.completed_at ?? s.submitted_at,
      sla_hours: s.risk_level === 'CRITICAL' ? 4 : s.risk_level === 'HIGH' ? 24 : 48,
      due_at: s.completed_at ?? s.submitted_at,
      history: [
        {
          code: 'intake_received',
          label: 'Intake Received',
          status: 'completed',
          timestamp: s.submitted_at,
          detail: 'Complaint was captured by the synthetic fallback pipeline.',
        },
        {
          code: 'routed',
          label: 'Routed To Team',
          status: 'completed',
          timestamp: s.completed_at ?? s.submitted_at,
          detail: `Complaint routed to ${s.assigned_team ?? 'Retail Banking Operations Team'}.`,
        },
      ],
    },
    audit_trail: [],
    total_processing_time_ms: s.processing_time_ms,
  };
}
